### ISSUE TITLE
Wrong build instructions

### ISSUE THREAD

**Issue by simendsjo** [bohonghuang/claw-raylib#2]
It says the prebuild branch makes it unnecessary to build the dependencies, but the third step tries to compile a c file which doesn't exist in the branch.

**Comment by bohonghuang** [comment]
Could you please provide the detailed error message?

**Comment by bohonghuang** [comment]
Well, my apologies for the oversight. I forgot to upload the `lib` folder. I have now uploaded it with the commit 4e8e0255dbefe6dafb64223a2aac7f8d176ba62a. Please fetch the latest update and run `git reset --hard` to the origin on your local branch.

**Comment by simendsjo** [comment]
Thanks. It still needed the raylib and raygui headers, so I added -I to the script, but then it worked fine! I'm seeing if claw-raylib can fit better than claylib as claylib seem a bit stalled and I'm unable to use some gui elements.

**Comment by bohonghuang** [comment]
> I'm seeing if claw-raylib can fit better than claylib as claylib seem a bit stalled and I'm unable to use some gui elements.

`claw-raylib` does not provide any functionality beyond what Raylib offers. It simply exposes all of Raylib's APIs in Lisp style with high performance and keeps up with Raylib's updates. I am currently using it to create a lightweight, dedicated game engine for developing my game with Lisp.

**Comment by fosskers** [comment]
This can probably be closed.
