### ISSUE TITLE
Prebuild with SDL backend?

### ISSUE THREAD

**Issue by simendsjo** [bohonghuang/claw-raylib#5]
Is it possible to get a prebuild version with the new PLATFORM_DESKTOP_SDL? Ray's hinting that it might solve a problem I'm having with input where remapped keys isn't reported correctly.

I really don't want to build LLVM on my poor laptop :sweat_smile:

**Comment by bohonghuang** [comment]
I have trouble understanding the difficulties you're facing. The `prebuild` branch still requires a C compiler available on your computer to compile the adapters for your machine architecture. If you're referring to the code generation part, it is independent of the backend used by Raylib. You can use the pre-generated code available in the `prebuild` branch in conjunction with the Raylib using SDL2 backend. If you need to switch the backend used by Raylib, you will need to specify SDL2 as the backend in the compilation options and manually compile Raylib into a dynamic link library.

**Comment by simendsjo** [comment]
> I have trouble understanding the difficulties you're facing.

I have mapped caps to ctrl, but when I press caps, Raylib doesn't see it as ctrl being pressed. All other applications work, so it might be a glfw issue, which is why I was recommended to try the SDL backend.

> If you're referring to the code generation part, it is independent of the backend used by Raylib. 

I just assumed it wasn't fully API compatible, but if the pre-generated code is still a match even when changing to the SDL backend, I'll try this.

Thanks!
