### ISSUE TITLE
Get the error `System "claw-raylib.raylib" not found` while loading the .asd file

### ISSUE THREAD

**Issue by sakurawald** [bohonghuang/claw-raylib#8]
Evaluate the form in lisp repl
```
(ql:quickload 'eon)
To load "eon":
  Load 1 ASDF system:
    eon
; Loading "eon"
..
```

Get the error
![image](https://github.com/user-attachments/assets/518f024e-7bf8-4521-8149-c3ab6a261fc9)

**Comment by bohonghuang** [comment]
It seems you didn't have `claw-raylib` properly installed. Clone the project into `~/quicklisp/local-projects` and follow the build instructions.

**Comment by sakurawald** [comment]
Failed to compile the llvm in my machine, so i git clone the `prebuild` branch, skip the step 1 and step2.

In step 3, i eval the form in repl
```
(let ((arch "x86_64-pc-linux-gnu")
               (path (merge-pathnames #P"lib/" (asdf:component-pathname (asdf:find-system '#:claw-raylib)))))
           (dolist (lib '("raylib" "rlgl"))
             (uiop:run-program
              (list "gcc" "-O3" "-fPIC" "-shared" "-o"
                    (namestring (merge-pathnames (format nil "lib~A-adapter.so" lib) path))
                    (namestring (merge-pathnames (format nil "lib~A-adapter.~A.c" lib arch) path))))))
```
It succeed.

**Comment by sakurawald** [comment]
The readme says
> claw-raylib does not ship any prebuilt binary files. You need to ensure that Raylib, Raygui, and a compatible C compiler are installed on your system to manually build the adapters required by claw.

The `raylib` is installed via `yay -S raylib`. However, i didn't figure out how to install the `raygui`.

![image](https://github.com/user-attachments/assets/4845daa0-b88a-4c1f-8b99-aafe945679f2)

**Comment by bohonghuang** [comment]
> The raylib is installed via yay -S raylib. However, i didn't figure out how to install the raygui.

Raygui is optional, without which the system can be loaded while the `raygui` package will not present.

**Comment by sakurawald** [comment]
> > The raylib is installed via yay -S raylib. However, i didn't figure out how to install the raygui.
> 
> Raygui is optional, without which the system can be loaded while the `raygui` package will not present.

Yeah, but i would like to use `raygui`.

**Comment by bohonghuang** [comment]
> > > The raylib is installed via yay -S raylib. However, i didn't figure out how to install the raygui.
> > 
> > Raygui is optional, without which the system can be loaded while the `raygui` package will not present.
> 
> Yeah, but i would like to use `raygui`. And if i delete the `raygui` in step 3, then the missing of `raygui` package will cause the quickload faliled to load the system, at least the `examples` system.

Please refer to the typical installation steps for C libraries, which involve copying `raygui.h` to `/usr/local/include` and copying your compiled `libraygui.so` to `/usr/local/lib`.

**Comment by sakurawald** [comment]
> > > > The raylib is installed via yay -S raylib. However, i didn't figure out how to install the raygui.
> > > 
> > > 
> > > Raygui is optional, without which the system can be loaded while the `raygui` package will not present.
> > 
> > 
> > Yeah, but i would like to use `raygui`. And if i delete the `raygui` in step 3, then the missing of `raygui` package will cause the quickload faliled to load the system, at least the `examples` system.
> 
> Please refer to the typical installation steps for C libraries, which involve copying `raygui.h` to `/usr/local/include` and copying your compiled `libraygui.so` to `/usr/local/lib`.

Okay thank you, now i have some trouble to compile the `.so` file for `raygui`, after i fix this, i will test and see if the step 3 can succeed or not.

**Comment by sakurawald** [comment]
Seems the same:
```
[root@archlinux lib]# pwd
/usr/local/lib
[root@archlinux lib]# ls
libraylib.so  libraylib.so.5.5.0  libraylib.so.550  raygui.so
```
And
```
[root@archlinux lib]# cd /usr/local/include/
[root@archlinux include]# ls
raygui.h  raylib.h  raymath.h  rlgl.h
```

![image](https://github.com/user-attachments/assets/d50e7bf8-47b8-487b-86b2-9233d23f95c9)

**Comment by sakurawald** [comment]
The `raylib.so` and `raygui.so`.

![image](https://github.com/user-attachments/assets/bd9d65b9-e925-416f-9d14-72dd472882c3)

**Comment by bohonghuang** [comment]
The library file should be named `libraygui.so`, and if I remember correctly, on ArchLinux, `/usr/local/lib` is not a default load path. You may need to consider modifying `ld.so.conf`.

**Comment by bohonghuang** [comment]
Of course, if you are not a neat freak, you can directly place `libraygui.so` in `/usr/lib`, which is the simplest and just works.

**Comment by sakurawald** [comment]
> Of course, if you are not a neat freak, you can directly place `libraygui.so` in `/usr/lib`, which is the simplest and just works.

Sadly, i rename the compiled `raygui.so` to `libraygui.so`, and copy this to `/usr/lib`.
Still get the same error.
```
[root@archlinux lib]# pwd
/usr/lib
[root@archlinux lib]# ls | grep libray
libraygui.so
libraylib.so
libraylib.so.4.5.0
libraylib.so.450
[root@archlinux lib]#
```

![image](https://github.com/user-attachments/assets/38c9b7e0-31dc-4577-ac6d-a4105ef43bc4)

**Comment by bohonghuang** [comment]
> > Of course, if you are not a neat freak, you can directly place `libraygui.so` in `/usr/lib`, which is the simplest and just works.
> 
> Sadly, i rename the compiled `raygui.so` to `libraygui.so`, and copy this to `/usr/lib`.
> Still get the same error.
> ```
> [root@archlinux lib]# pwd
> /usr/lib
> [root@archlinux lib]# ls | grep libray
> libraygui.so
> libraylib.so
> libraylib.so.4.5.0
> libraylib.so.450
> [root@archlinux lib]#
> ```
> 
> ![image](https://github.com/user-attachments/assets/38c9b7e0-31dc-4577-ac6d-a4105ef43bc4)
> 

Did you you place `raygui.h` in `/usr/include`? It's recommended to execute the command in shell to reveal the details of this error.

**Comment by sakurawald** [comment]
I use the command 
```
gcc -O3 -fPIC -shared -o /home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraygui-adapter.so /home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraygui-adapter.x86_64-pc-linux-gnu.c
```
To build the `libraygui-adapter.so` successfully.

However, while i try to quickload the system, it fails, since like the abi is not compatible.


![image](https://github.com/user-attachments/assets/a95731ea-34c6-40ea-9ccd-ebbd421001d6)

**Comment by sakurawald** [comment]
> raygui.h

After i place the `raygui.h` in `/usr/include`, still get the same error:
![image](https://github.com/user-attachments/assets/ab0eab4a-a66e-43ba-a153-97ce8f65e9c9)

**Comment by sakurawald** [comment]
Now, the `adapter` for `libgui` is compiled successfully.
However, failed to load the foreign library.

![image](https://github.com/user-attachments/assets/370a44f0-6b54-40cf-82e9-6f6f22baa8b9)

**Comment by bohonghuang** [comment]
> Now, the `adapter` for `libgui` is compiled successfully.
> However, failed to load the foreign library.
> 
> ![image](https://github.com/user-attachments/assets/370a44f0-6b54-40cf-82e9-6f6f22baa8b9)
> 

Could you successfully load `claw-raylib` without `raygui` before?

**Comment by sakurawald** [comment]
> > Now, the `adapter` for `libgui` is compiled successfully.
> > However, failed to load the foreign library.
> > ![image](https://private-user-images.githubusercontent.com/10484271/384876487-370a44f0-6b54-40cf-82e9-6f6f22baa8b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMTk5OTgsIm5iZiI6MTczMTMxOTY5OCwicGF0aCI6Ii8xMDQ4NDI3MS8zODQ4NzY0ODctMzcwYTQ0ZjAtNmI1NC00MGNmLTgyZTktNmY2ZjIyYmFhOGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDEwMDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjZDg3MGI0NjI0MmQxZDJhMzJhM2JiOTYzNjZjZTYyYzExZmE4NTI0NWE3NjNhNmIwYmM4YjM2MmI3NzJhMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yZoJ3nA11dKblrds8hc1EX5sB_OlVnJHqWaPuauKAV4)
> 
> Could you successfully load `claw-raylib` without `raygui` before?

Actually, i never load the `claw-raylib` system successfully .
![image](https://github.com/user-attachments/assets/830af975-e4d0-4298-b91a-3e4374b5aac5)

**Comment by sakurawald** [comment]
I follow the manual to git clone the latest commit in `raylib` repository, and use `make install` to install the `raylib` in the correct location in my host os.
After i install the `raylib` properly, i am able to compile `raygui` now.
So then i compile the `raygui` following the official manual, and get the `raygui.so` file.

**Comment by bohonghuang** [comment]
> I follow the manual to git clone the latest commit in `raylib` repository, and use `make install` to install the `raylib` in the correct location in my host os.
> After i install the `raylib` properly, i am able to compile `raygui` now.
> So then i compile the `raygui` following the official manual, and get the `raygui.so` file.

Please be aware that the API of the latest Raylib is not compatible with the released 5.0 version.

**Comment by bohonghuang** [comment]
> Actually, i never load the claw-raylib system successfully .

I suggest you install the 5.0 version of Raylib via package manager, and load `claw-raylib` without `raygui` in the first place.

**Comment by bohonghuang** [comment]
Then download the released 4.0 version of Raygui, compile it to `libraygui.so`, and place it in `/usr/lib/`.

**Comment by sakurawald** [comment]
I will try it later.

**Comment by sakurawald** [comment]
> > Actually, i never load the claw-raylib system successfully .
> 
> I suggest you install the 5.0 version of Raylib via package manager, and load `claw-raylib` without `raygui` in the first place.

Sadly, in my env, you have to compile the `raylib` from source, or your can't compile `raygui`.

```
╰─ yay -Si raylib                                                                                                                                  ─╯
Repository      : extra
Name            : raylib
Version         : 5.0-1
Description     : Simple and easy-to-use game programming library
Architecture    : x86_64
URL             : https://www.raylib.com
Licenses        : ZLIB
Groups          : None
Provides        : None
Depends On      : None
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 916.60 KiB
Installed Size  : 2783.87 KiB
Packager        : Alexander F. Rødseth <xyproto@archlinux.org>
Build Date      : Sun 19 Nov 2023 08:24:19 PM CST
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```

Actually, i install the `raylib` via `pacman` the package manager first, and i found that while i am compiling the `raygui` from source, the gcc says it can't find the links from `raylib`.
And then i have to compile the `raylib` from source, using `make install ...` to install the `raylib`. After that, i am able to compile `raygui` and get `raygui.so` file.

**Comment by sakurawald** [comment]
If i delete the `libraylib.so` file in `/usr/local/lib`, then i will failed to compile the `adapter` for `raylib`. (That's to say, the `raylib` installed via `package manager` didn't provided the information that the gcc needs. This is why i have to compile the `raylib` from source, and use `make install ...` to install it to `/usr/local/lib`.

```
╰─ gcc -O3 -fPIC -shared -o /home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.so /home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c

/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c: In function ‘__claw_IsTextureReady’:
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c:2004:8: error: implicit declaration of function ‘IsTextureReady’ [-Wimplicit-function-declaration]
 2004 | return IsTextureReady(*texture);
      |        ^~~~~~~~~~~~~~
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c: In function ‘__claw_IsShaderReady’:
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c:2029:8: error: implicit declaration of function ‘IsShaderReady’ [-Wimplicit-function-declaration]
 2029 | return IsShaderReady(*shader);
      |        ^~~~~~~~~~~~~
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c: In function ‘__claw_IsImageReady’:
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c:2163:8: error: implicit declaration of function ‘IsImageReady’ [-Wimplicit-function-declaration]
 2163 | return IsImageReady(*image);
      |        ^~~~~~~~~~~~
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c: In function ‘__claw_IsSoundReady’:
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c:2245:8: error: implicit declaration of function ‘IsSoundReady’ [-Wimplicit-function-declaration]
 2245 | return IsSoundReady(*sound);
      |        ^~~~~~~~~~~~
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c: In function ‘__claw_IsFontReady’:
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c:2250:8: error: implicit declaration of function ‘IsFontReady’ [-Wimplicit-function-declaration]
 2250 | return IsFontReady(*font);
      |        ^~~~~~~~~~~
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c: In function ‘__claw_IsMusicReady’:
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c:2305:8: error: implicit declaration of function ‘IsMusicReady’ [-Wimplicit-function-declaration]
 2305 | return IsMusicReady(*music);
      |        ^~~~~~~~~~~~
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c: In function ‘__claw_IsAudioStreamReady’:
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c:2355:8: error: implicit declaration of function ‘IsAudioStreamReady’; did you mean ‘IsAudioStreamValid’? [-Wimplicit-function-declaration]
 2355 | return IsAudioStreamReady(*stream);
      |        ^~~~~~~~~~~~~~~~~~
      |        IsAudioStreamValid
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c: In function ‘__claw_LoadImageSvg’:
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c:2468:21: error: implicit declaration of function ‘LoadImageSvg’; did you mean ‘LoadImageRaw’? [-Wimplicit-function-declaration]
 2468 | (*__claw_result_) = LoadImageSvg(fileNameOrString, width, height);
      |                     ^~~~~~~~~~~~
      |                     LoadImageRaw
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c:2468:21: error: incompatible types when assigning to type ‘Image’ from type ‘int’
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c: In function ‘__claw_IsWaveReady’:
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c:2693:8: error: implicit declaration of function ‘IsWaveReady’ [-Wimplicit-function-declaration]
 2693 | return IsWaveReady(*wave);
      |        ^~~~~~~~~~~
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c: In function ‘__claw_DrawRectangleRoundedLines’:
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c:3345:54: error: incompatible type for argument 4 of ‘DrawRectangleRoundedLines’
 3345 | DrawRectangleRoundedLines(*rec, roundness, segments, lineThick, *color);
      |                                                      ^~~~~~~~~
      |                                                      |
      |                                                      float
In file included from /home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c:10:
/usr/local/include/raylib.h:1275:90: note: expected ‘Color’ but argument is of type ‘float’
 1275 | RLAPI void DrawRectangleRoundedLines(Rectangle rec, float roundness, int segments, Color color);         // Draw rectangle lines with rounded edges
      |                                                                                    ~~~~~~^~~~~
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c:3345:1: error: too many arguments to function ‘DrawRectangleRoundedLines’
 3345 | DrawRectangleRoundedLines(*rec, roundness, segments, lineThick, *color);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/raylib.h:1275:12: note: declared here
 1275 | RLAPI void DrawRectangleRoundedLines(Rectangle rec, float roundness, int segments, Color color);         // Draw rectangle lines with rounded edges
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c: In function ‘__claw_IsRenderTextureReady’:
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c:3520:8: error: implicit declaration of function ‘IsRenderTextureReady’; did you mean ‘IsRenderTextureValid’? [-Wimplicit-function-declaration]
 3520 | return IsRenderTextureReady(*target);
      |        ^~~~~~~~~~~~~~~~~~~~
      |        IsRenderTextureValid
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c: In function ‘__claw_IsMaterialReady’:
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c:3697:8: error: implicit declaration of function ‘IsMaterialReady’; did you mean ‘IsMaterialValid’? [-Wimplicit-function-declaration]
 3697 | return IsMaterialReady(*material);
      |        ^~~~~~~~~~~~~~~
      |        IsMaterialValid
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c: In function ‘__claw_IsModelReady’:
/home/sakurawald/.roswell/lisp/quicklisp/local-projects/claw-raylib/lib/libraylib-adapter.x86_64-pc-linux-gnu.c:4276:8: error: implicit declaration of function ‘IsModelReady’ [-Wimplicit-function-declaration]
 4276 | return IsModelReady(*model);
      |        ^~~~~~~~~~~~
```

**Comment by bohonghuang** [comment]
> If i delete the libraylib.so file (i compiled from source from latest commit) in /usr/local/lib, then i will failed to compile the adapter for raylib. 

Hmm... If you have to compile Raylib from source, please go with the release version instead of the latest, which is not compatible with the pre-generated adapters. Please note that the adapters were generated against Raylib 5.0 and Raygui 4.0, as written in the commit message.

**Comment by sakurawald** [comment]
It works after i git clone the commit ae50bfa2cc569c0f8d5bc4315d39db64005b1b08 in `raylib`, compile and copy the `libraylib.so` file to `/usr/local/lib`. (The `make install ...` will copy the compiled .so file to proper location.)

And then git clone the commit 25c8c65a6e5f0f4d4b564a0343861898c6f2778b in `raygui`, compile and copy the `raygui.so` file and rename to `/usr/local/lib/libraygui.so`. (Here i need to copy the compiled .so shared file for `raygui`.)

Also remember to replace the `raygui.h` file in `/usr/include` with the `v4.0` version.

![image](https://github.com/user-attachments/assets/bbefd1c1-86f0-439e-b240-813ea7e80c21)
